# Generated by Django 5.0.6 on 2024-07-11 08:26

import django.core.validators
import video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='jesmar', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(null=True, upload_to='videos_uploaded/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('MOV', 'avi', 'mp4', 'webm', 'mkv'))])),
                ('thumbnail', models.ImageField(upload_to='thumbnail/%Y/%m/%d', validators=[django.core.validators.validate_image_file_extension])),
                ('details', models.CharField(max_length=2000)),
                ('tags', models.JSONField(default=video.models.UploadedVideo.default_tags)),
                ('playlists', models.CharField(blank=True, max_length=100)),
                ('visibility', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], max_length=3)),
                ('datetime_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
