# Generated by Django 5.0.6 on 2024-07-11 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_rename_playlists_uploadedvideo_playlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedvideo',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('MOV', 'avi', 'mp4', 'webm', 'mkv'))]),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='visibility',
            field=models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], default='Public', max_length=3),
        ),
    ]
