# Generated by Django 5.0.6 on 2024-07-14 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_alter_uploadedvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideo',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('MOV', 'avi', 'mp4', 'webm', 'mkv'))]),
        ),
    ]
