# Generated by Django 5.0.6 on 2024-07-24 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_alter_uploadedvideo_owner_alter_uploadedvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('MOV', 'avi', 'mp4', 'webm', 'mkv'))]),
        ),
    ]
