# Generated by Django 5.0.6 on 2024-07-24 04:53

import django.core.validators
import video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_alter_uploadedvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedvideo',
            name='playlist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='tags',
            field=models.JSONField(blank=True, default=video.models.UploadedVideo.default_tags, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('MOV', 'avi', 'mp4', 'webm', 'mkv'))]),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='visibility',
            field=models.CharField(blank=True, choices=[('PU', 'Public'), ('PR', 'Private')], default='Public', max_length=3, null=True),
        ),
    ]
