# Generated by Django 5.0.6 on 2024-07-25 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_alter_uploadedvideo_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('MOV', 'avi', 'mp4', 'webm', 'mkv'))]),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='visibility',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=7, null=True),
        ),
    ]
